[package]
name = "rustforge-graphics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rustforge-core = { path = "../rustforge-core" }
rustforge-ecs = { path = "../rustforge-ecs" }
specs = { workspace = true }
specs-derive = { workspace = true }
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
winit = { workspace = true }
ash = { workspace = true, optional = true }
shaderc = { workspace = true }
image = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
pixels = { workspace = true }
wgpu = { workspace = true }
fontdue = "0.8"

# Dependencies for examples
[dev-dependencies]
winit = { workspace = true }
pollster = "0.3"
raw-window-handle = "0.5"
env_logger = { workspace = true }

[features]
default = []
low-level = ["ash"]
